### ISSUE TITLE
Cross reference export

### ISSUE THREAD

**Issue by pemocarlo** [andras-simonyi/citeproc-orgref#13]
Hi!
First of all, thank you for this wonderful package, works great!

I am not sure if it would be in the scope, but would it be possible to get the cross-references of figures and tables from org-ref with the correct numbering, instead of just the link?

Thank you in advance

**Comment by andras-simonyi** [comment]
Hi, I'm glad that you find the package useful, thanks for the feedback! 

As for your question, citeproc-org deals only with the export of cite links in Org  documents, cross references should be handled by org-ref itself.  So unless the problem is caused by citeproc-org (experienced only when citeproc-org is activated) then you should probably open an org-ref issue about it.

**Comment by pemocarlo** [comment]
Thanks for your prompt reply!

I realized I wasn't too specific. The numbering of org-ref cross references does not work when exporting to ODT or HTML, LaTeX works fine. And it is definitely not caused by citeproc-org.

Based on your reply I now understand this is not meant to be solved by citeproc-org, so I will check if there is a solution from org-ref. I will close this thread accordingly.
