### ISSUE TITLE
noexport and bibliography position

### ISSUE THREAD

**Issue by matzebond** [andras-simonyi/citeproc-orgref#15]
```
#+BIBLIOGRAPHY: ~/zotero.bib

* Start
  I am citing cite:schwartz_green_2019

* End
  an other cite cite:sandler_mobilenetv2_2018

#+BIBLIOGRAPHY: here

* Notes                                                            :noexport:
** Todos
*** TODO report issue
   lorem ipsum
```

In the following the bibliography is not exported. When I move the Notes headline to the top it works.

**Comment by andras-simonyi** [comment]
Hello, 
thanks for the report! It seems that the problem comes from the fact that you are mixing the two supported citation/bibliography syntaxes: org-ref and the WIP Org built-in syntax. Your citations are according to the org-ref syntax (they are cite links) but the bibliography specifications are Org keywords instead of a single org-ref bibliography link. Unless you want to experiment with the WIP built-in syntax which requires a seperate Org branch you should use bibliography links, that is, just have a single

    bibliography:~/zotero.bib

line where you have "#+BIBLIOGRAPHY: here" now, and the starting '"#+BIBLIOGRAPHY: ~/zotero.bib" should be removed as well. I hope these changes will solve the problem.

**Comment by matzebond** [comment]
You are absolutely right. I misread the readme but it's very clearly stated there. 
Exporting to html works fine and the Notes heading is not exported. Thanks!
